pipeline{
    agent{
        label "nodejs"
    }
    stages{
        stage('Release') {
            steps {
                sh '''
                    oc project RHT_OCP4_DEV_USER-greetings
                    oc start-build greeting-console  --follow --wait
                '''
            }
         }                
    }
}
