pipeline{
    agent{
        label "nodejs"
    }
    stages{
        stage('Release') {
            steps {
                sh '''
                    oc project amb-infra
                    oc start-build greeting-console  --follow --wait
                    
                '''
            }
         }                
    }
}
